### PR TITLE
Varna colormap

### PR DESCRIPTION
**Pull request by njbooher**

### CODE REVIEW

**Comment by rjandr** [comment]
I think we just need to reverse the colormap list when the strand is set to reverse. But should be good to go after that.

**Comment by njbooher** [comment]
Does it not already do this?

https://github.com/ResearchIT/IGV-ScanFold/blob/master/ScanFold/ScanFold-Fold_IGV.py#L424

**Comment by rjandr** [comment]
Yeah it reverses correctly for genome viewing (3' to 5') but when we show the structure (in 5' to 3') we need to flip it back.

**Comment by njbooher** [comment]
Like this?

https://github.com/ResearchIT/IGV-ScanFold/actions/runs/742484930
https://github.com/ResearchIT/IGV-ScanFold/actions/runs/742485285

**Comment by rjandr** [comment]
> Like this?
> 
> https://github.com/ResearchIT/IGV-ScanFold/actions/runs/742484930
> https://github.com/ResearchIT/IGV-ScanFold/actions/runs/742485285

That does it!

**Pull request merged**
